apiVersion: apps/v1
kind: Deployment
metadata:
  name: latestgreeting 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
        volumes:
          - name: application-config
            configMap:
             name: application-file   
          
        containers:
          - name: latestgreeting
            image: dvarshney86/newrelic:1.1
            volumeMounts:
              - name: application-config
                mountPath: /test/ 
 
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002